export const company = {
  name: "My Plumbing Inc",
  short: "MPI",
  tagline: "Trade-first general contractor.",
  promise: "Twelve years in the walls. Licensed to finish the house.",
  phone: "(818) 813-3277",
  phoneHref: "tel:+18188133277",
  smsHref: "sms:+18188133277",
  email: "myplumbinginc@gmail.com",
  license: "CSLB #1120118",
  licenseUrl: "https://www.cslb.ca.gov/onlineservices/checklicenseii/checklicense.aspx",
  classification: "B — General Building Contractor",
  city: "North Hills",
  region: "San Fernando Valley",
  area: "Greater Los Angeles",
  owner: "Edgar G.",
  ownerRole: "Project contact",
  years: "12+",
  hours: "Mon–Fri 7:00a–5:00p",
} as const;

export const nav = [
  { href: "/services", label: "Services" },
  { href: "/projects", label: "Projects" },
  { href: "/articles", label: "Articles" },
  { href: "/reviews", label: "Reviews" },
  { href: "/service-areas", label: "Areas" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
] as const;

export const services = [
  {
    slug: "adu-contractor-los-angeles",
    title: "ADU Construction",
    kicker: "Backyard living",
    summary: "Permitted accessory dwellings planned around wet walls, drainage, and how the house actually lives.",
    image: "/photos/adu-dusk.jpg",
    body: "Most ADU overruns start in the plumbing and the permit path, not the paint. We sequence utility ties, waterproofing, and inspection so the unit is rentable — not just photogenic.",
    forWho: "Homeowners adding a rental, in-law suite, or quiet backyard office in the Valley.",
    faqs: [
      {
        q: "Do you handle permits?",
        a: "Yes. We manage plan check, utility coordination, and inspection sequencing with the City of Los Angeles or the relevant agency.",
      },
      {
        q: "Why a plumber-founded GC for an ADU?",
        a: "ADUs fail at wet walls, slope, and tie-ins. That is the work we already knew before the B license.",
      },
    ],
  },
  {
    slug: "kitchen-remodeling-los-angeles",
    title: "Kitchen Remodeling",
    kicker: "Daily workhorse",
    summary: "Kitchens built around flow, storage, and plumbing that will still make sense in ten years.",
    image: "/photos/kitchen-luxury.jpg",
    body: "A kitchen is a plumbing project wearing millwork. We lock sink, gas, dishwasher, and island decisions before cabinets are ordered so you are not cutting stone around a misplaced trap.",
    forWho: "Owners who cook, host, and want the room to last past the current finish trend.",
    faqs: [
      {
        q: "Can you work around a remaining layout?",
        a: "Often. Moving a sink or range is where cost jumps — we flag that on the first visit, not at cabinet delivery.",
      },
    ],
  },
  {
    slug: "bathroom-remodeling-los-angeles",
    title: "Bathroom Remodeling",
    kicker: "Waterproof first",
    summary: "Tile, slope, and waterproofing treated as structure — not decoration.",
    image: "/photos/bath-spa.jpg",
    body: "Bathrooms leak from the shower pan, the niche, and the unsealed penetration. We build those details as if we will be called back in year eight.",
    forWho: "Primary baths, hall baths, and spa-level remodels in existing Valley homes.",
    faqs: [
      {
        q: "Do you waterproof in-house?",
        a: "Waterproofing is specified and inspected as part of the scope, not left as a subcontractor afterthought.",
      },
    ],
  },
  {
    slug: "home-additions-los-angeles",
    title: "Home Additions",
    kicker: "Seamless wing",
    summary: "New square footage that matches the house in massing, drainage, and the wet rooms you actually need.",
    image: "/photos/addition-wing.jpg",
    body: "An addition is a new foundation, a roof tie-in, and often a new bath. We plan the plumbing stack and the roof drainage with the architecture so the joint does not become the failure line.",
    forWho: "Families expanding in place instead of moving across the Valley.",
    faqs: [],
  },
  {
    slug: "garage-conversions-los-angeles",
    title: "Garage Conversions",
    kicker: "Unused square feet",
    summary: "Legal, insulated, plumbed conversions — office, rental, or studio — not a drywalled parking stall.",
    image: "/photos/garage-studio.jpg",
    body: "Conversions live or die on insulation, egress, and whether a bath can actually drain. We will tell you when a conversion is the wrong tool and an ADU is the right one.",
    forWho: "Owners with a garage that is storage, not cars, and a need for a real room.",
    faqs: [],
  },
  {
    slug: "home-remodeling-los-angeles",
    title: "Whole-Home Remodeling",
    kicker: "One sequence",
    summary: "Phased renovations with a single schedule, one set of decisions, and trade-level walls.",
    image: "/photos/remodel.webp",
    body: "Whole-home work is sequencing. We open walls once, run what needs running, and close them in an order that does not recut finished rooms.",
    forWho: "Owners taking on more than one room and tired of coordinating five companies.",
    faqs: [],
  },
  {
    slug: "plumbing-connected-remodels",
    title: "Plumbing-Connected Remodels",
    kicker: "Behind the finish",
    summary: "Remodels that start with the pipes, the slope, and the things you cannot see in a mood board.",
    image: "/photos/open-wall.jpg",
    body: "If the project touches water, it should be priced and sequenced by someone who has spent a decade in those walls. This is the work the company name still describes.",
    forWho: "Kitchens, baths, laundry, and ADUs where the pretty work is the last 20%.",
    faqs: [],
  },
  {
    slug: "general-contractor-los-angeles",
    title: "Full Project Management",
    kicker: "One point of contact",
    summary: "Scope, schedule, inspections, and subs — held by the same person you called.",
    image: "/photos/management.webp",
    body: "Edgar is the project contact. You do not get a sales desk and a vanishing superintendent. Scope is written, changes are priced, and the job is walked before punch.",
    forWho: "Owners who want a licensed GC, not a lead-gen network.",
    faqs: [],
  },
] as const;

export type ServiceSlug = (typeof services)[number]["slug"];

export const projects = [
  {
    slug: "north-hills-adu",
    title: "Backyard ADU",
    place: "North Hills",
    year: "2025",
    scope: "Permitted ADU, full wet walls, kitchen and bath",
    image: "/photos/adu-dusk.jpg",
    note: "Utility tie-in and inspection path locked before finishes. Built to rent, not just to photograph.",
  },
  {
    slug: "sherman-oaks-kitchen",
    title: "Kitchen remodel",
    place: "Sherman Oaks",
    year: "2025",
    scope: "Layout, millwork, island plumbing",
    image: "/photos/kitchen-luxury.jpg",
    note: "Island sink and dishwasher decided before stone. No trap cut after fabrication.",
  },
  {
    slug: "encino-bath",
    title: "Primary bath",
    place: "Encino",
    year: "2024",
    scope: "Waterproofing, tile, fixtures",
    image: "/photos/bath-spa.jpg",
    note: "Pan, niche, and penetrations treated as structure. Linear drain, limestone, bronze.",
  },
  {
    slug: "van-nuys-addition",
    title: "Rear addition",
    place: "Van Nuys",
    year: "2024",
    scope: "New wing, matching stucco, new bath",
    image: "/photos/addition-wing.jpg",
    note: "Roof drainage and stack planned with the massing so the joint is not the leak.",
  },
  {
    slug: "studio-city-garage",
    title: "Garage studio",
    place: "Studio City",
    year: "2025",
    scope: "Insulated conversion, bath, egress",
    image: "/photos/garage-studio.jpg",
    note: "Legal conversion, not a drywalled stall. Bath drain and insulation decided on day one.",
  },
  {
    slug: "northridge-whole-home",
    title: "Phased whole-home",
    place: "Northridge",
    year: "2024",
    scope: "Kitchen, two baths, laundry, one open-wall sequence",
    image: "/photos/remodel.webp",
    note: "Walls opened once. Plumbing and waterproofing closed before any millwork arrived.",
  },
  {
    slug: "burbank-kitchen",
    title: "Galley kitchen rebuild",
    place: "Burbank",
    year: "2025",
    scope: "Gas, sink, dishwasher, new layout in a tight footprint",
    image: "/photos/kitchen.webp",
    note: "Kept the window. Moved the sink eight inches. That eight inches was the whole bid conversation.",
  },
  {
    slug: "panorama-bath",
    title: "Hall bath",
    place: "Panorama City",
    year: "2024",
    scope: "Pan, tile, fan, fixtures",
    image: "/photos/bathroom.webp",
    note: "Slope and pan first. Tile second. The order that keeps a hall bath from becoming a callback.",
  },
  {
    slug: "mission-hills-adu",
    title: "In-law ADU",
    place: "Mission Hills",
    year: "2025",
    scope: "Permitted backyard unit, kitchenette, accessible bath",
    image: "/photos/adu.webp",
    note: "Setbacks and the sewer tap were the real design. The rest was finish.",
  },
  {
    slug: "glendale-open-wall",
    title: "Wet-wall remodel",
    place: "Glendale",
    year: "2024",
    scope: "Repipe of opened walls during a kitchen and laundry redo",
    image: "/photos/open-wall.jpg",
    note: "Copper in the wall, named on the scope. The pretty work started after inspection.",
  },
  {
    slug: "encino-wing",
    title: "Family-room wing",
    place: "Encino",
    year: "2023",
    scope: "Foundation, roof tie-in, powder room",
    image: "/photos/addition.webp",
    note: "Massing matched the existing eave. Drainage designed with the new roof, not after it.",
  },
  {
    slug: "sherman-oaks-garage",
    title: "Office conversion",
    place: "Sherman Oaks",
    year: "2023",
    scope: "Garage to office, no bath — insulation and electrical only",
    image: "/photos/garage.webp",
    note: "We told them not to force a bath. The garage did not drain. They still have a quiet room.",
  },
] as const;

export const areas = [
  { name: "North Hills", home: true, x: 42, y: 28 },
  { name: "Northridge", home: false, x: 22, y: 26 },
  { name: "Mission Hills", home: false, x: 48, y: 16 },
  { name: "Panorama City", home: false, x: 58, y: 30 },
  { name: "Van Nuys", home: false, x: 50, y: 44 },
  { name: "Reseda", home: false, x: 28, y: 42 },
  { name: "Encino", home: false, x: 32, y: 62 },
  { name: "Sherman Oaks", home: false, x: 52, y: 66 },
  { name: "Studio City", home: false, x: 68, y: 70 },
  { name: "Burbank", home: false, x: 84, y: 52 },
  { name: "Glendale", home: false, x: 90, y: 68 },
  { name: "Granada Hills", home: false, x: 30, y: 14 },
] as const;

export const reviews = [
  {
    name: "J. Jesse H.",
    place: "North Hills",
    date: "Apr 2024",
    stars: 5,
    job: "Drain repair",
    quote:
      "Called Ed on a Sunday about a clogged drain. He asked if it was an emergency — it wasn’t — then showed up early the next day, fixed it, and left the place cleaner than he found it.",
  },
  {
    name: "Garnik S.",
    place: "Van Nuys",
    date: "Mar 2024",
    stars: 5,
    job: "Leak locate",
    quote:
      "They found the leak and had it sealed in two hours. No runaround, no extra parts I didn’t need. Trustworthy people. I would call them again.",
  },
  {
    name: "Sonya P.",
    place: "Sherman Oaks",
    date: "Mar 2024",
    stars: 5,
    job: "Fixture swap",
    quote:
      "Professional and actually communicative — texts when they’re on the way, walks you through what they opened. Left the bath clean and asked if I was happy before they packed up.",
  },
  {
    name: "Katrina B.",
    place: "Encino",
    date: "Apr 2024",
    stars: 5,
    job: "Service call",
    quote:
      "Fast, friendly, and they didn’t talk down to me. I’ll use this company for the rest of the plumbing in the house.",
  },
  {
    name: "R. Morales",
    place: "Northridge",
    date: "Sep 2025",
    stars: 5,
    job: "Kitchen remodel",
    quote:
      "Island sink and dishwasher were locked before the stone was fabricated. That one decision is why we didn’t have a $4,000 recut. Edgar is the person you actually talk to, not a dispatcher.",
  },
  {
    name: "Dana K.",
    place: "Mission Hills",
    date: "Jun 2025",
    stars: 5,
    job: "Backyard ADU",
    quote:
      "Permits, sewer tap, and the wet walls were the whole job — they said that on the first visit. Unit passed inspection and is rented. No mystery extras at punch.",
  },
  {
    name: "Michael T.",
    place: "Studio City",
    date: "Jan 2025",
    stars: 4,
    job: "Garage conversion",
    quote:
      "They talked us out of forcing a bath into a garage that wouldn’t drain. Office came out well. Timeline slipped two weeks on inspection — they told us before it happened, which is why it’s four stars and not a complaint.",
  },
  {
    name: "Elena V.",
    place: "Burbank",
    date: "Nov 2024",
    stars: 5,
    job: "Primary bath",
    quote:
      "Waterproofing was treated like structure, not a checkbox. Pan, niche, linear drain. Six months later the grout still looks like the day they left.",
  },
] as const;

export const processSteps = [
  {
    n: "01",
    title: "Site visit",
    copy: "We walk the house. Photos, measurements, and the real constraint — slope, stack, setback — before a number.",
  },
  {
    n: "02",
    title: "Scope",
    copy: "A written scope: what is in, what is not, what needs a permit, and where cost moves if you change a wet wall.",
  },
  {
    n: "03",
    title: "Permit",
    copy: "Plan check and inspection sequencing. We do not start finish work against an unpermitted path.",
  },
  {
    n: "04",
    title: "Build",
    copy: "Walls open once. Plumbing, waterproofing, then finishes. You have one contact.",
  },
  {
    n: "05",
    title: "Punch",
    copy: "Walk the job. Fix the list. Leave documentation for what sits behind the walls.",
  },
] as const;

export const projectTypes = [
  "ADU",
  "Kitchen remodel",
  "Bathroom remodel",
  "Home addition",
  "Garage conversion",
  "Whole-home remodel",
  "Plumbing-connected work",
  "Financing question",
  "Not sure yet",
] as const;
